Fix behavior of Dry::System::Identifier#start_with?.
dry-rb/dry-system pull request #177
Opened 2021-05-04 20:52 UTC by wuarmin

Fix issue #176.

2021-05-04 21:01 UTC, flash-gordon requested changes

2021-05-04 21:01 UTC, flash-gordon commented on lib/dry/system/identifier.rb
>        end
It'll save a fair share of allocations
```ruby
identifier.eql?(leading_namespaces) || identifier.start_with?("#{leading_namespaces}#{separator}")
```

2021-05-04 21:17 UTC, wuarmin commented on lib/dry/system/identifier.rb
>        end
great input!

2021-05-05 09:19 UTC, flash-gordon approved these changes

2021-05-06 07:35 UTC, solnic approved these changes

2021-05-06 07:36 UTC, merged